name: algo_trade
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py313hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.13.11=hc7d8306_100_cp313
  - python_abi=3.13=3_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py313hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.4.0
      - async-generator==1.10
      - asyncio-extras==1.3.2
      - attrs==25.4.0
      - autobahn==24.4.2
      - blinker==1.9.0
      - certifi==2024.12.14
      - cffi==2.0.0
      - coloredlogs==15.0.1
      - cryptography==46.0.3
      - deprecated==1.2.18
      - fmclient==5.2.9b0
      - frozenlist==1.8.0
      - humanfriendly==10.0
      - hyperlink==21.0.0
      - idna==3.11
      - multidict==6.7.1
      - propcache==0.4.1
      - pycparser==3.0
      - pyjwt==2.10.1
      - pytz==2024.2
      - txaio==25.12.2
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/algo_trade
